services:
  - type: web
    name: n8n-selfhost-hormigasais
    env: docker
    plan: starter  # puedes cambiar a 'standard' si necesitas más recursos
    repo: https://github.com/HormigasAIS/n8n-selfhost-hormigasais
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "hormigas"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "clave-supersecreta123"  # cámbiala por seguridad
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: "https://n8n-selfhost-hormigasais.onrender.com/"
      - key: GENERIC_TIMEZONE
        value: "America/El_Salvador"
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
